source "https://api.berkshelf.com"


cookbook "redisio", ">= 1.2.2"
cookbook "nodejs", ">= 1.1.2"
cookbook "git", ">= 2.4.0"
cookbook "build-essential", ">= 1.3.4"
cookbook "apt", ">= 1.9.2"
cookbook "python", ">= 1.2.2"
cookbook "dmg", ">= 1.1.0"
cookbook "runit", ">= 1.1.2"
cookbook "ruby_build", ">= 0.7.2"
cookbook "vim", ">= 1.0.2"
